"Area:Accessibility":
  - '\[X\] Accessibility \(Web Accessibility\)'
"Area:Color":
  - '\[X\] Color'
"Area:Core":
  - '\[X\] Core'
"Area:Data":
  - '\[X\] Data'
"Area:DOM":
  - '\[X\] DOM'
"Area:Events":
  - '\[X\] Events'
"Area:Image":
  - '\[X\] Image'
"Area:IO":
  - '\[X\] IO \(Input/Output\)'
"Area:Math":
  - '\[X\] Math'
"Area:Typography":
  - '\[X\] Typography'
"Area:Utilities":
  - '\[X\] Utilities'
"Area:WebGL":
  - '\[X\] WebGL'
"Build Process":
  - '\[X\] Build tools and processes'
"Unit Testing":
  - '\[X\] Unit Testing'
"Localization":
  - '\[X\] Localization'
"Friendly Errors":
  - '\[X\] Friendly error system'
