"Area:Accessibility":
  - '\[X\] Accessibility'
"Area:Color":
  - '\[X\] Color'
"Area:Core":
  - '\[X\] Core'
"Area:Data":
  - '\[X\] Data'
"Area:DOM":
  - '\[X\] DOM'
"Area:Events":
  - '\[X\] Events'
"Area:Image":
  - '\[X\] Image'
"Area:IO":
  - '\[X\] IO'
"Area:Math":
  - '\[X\] Math'
"Area:Typography":
  - '\[X\] Typography'
"Area:Utilities":
  - '\[X\] Utilities'
"Area:WebGL":
  - '\[X\] WebGL'
"Build Process":
  - '\[X\] Build Tools'
"Unit Testing":
  - '\[X\] Unit Testing'
"Localization":
  - '\[X\] Localization Tools'
"Friendly Errors":
  - '\[X\] Friendly Errors'
