name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  type: checkboxes
  id: sub-area
  attributes:
    label: Most appropriate sub-area of p5.js?
    description: You may select more than one.
    options:
      - label: Accessibility
      - label: Build
      - label: Core
